---
sudo: false

language: ruby

cache: bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.3
  - ruby-head

before_install: 
  - gem install bundler -v 2.0.1

script: "bundle exec rake spec"

notifications:
  email: false
